name: Grupo 5

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    env:
      plataforma: reniec
      region: piura
      clase: HDD
    
    runs-on: ubuntu-latest
    
    steps:
      - name: "Prueba de mensajes"
        run: echo "Hola Grupo 5, bienvenidos"

      - name: "Variables creadas en el workflow"
        run: |
          echo "La plataforma es: ${{ env.plataforma }}"
          echo "La región es: ${{ env.region }}"
          echo "La clase es: ${{ env.clase }}"

      - name: "Variables del entorno del Github Actions"
        run: |
          echo "El repositorio es: $GITHUB_REPOSITORY"
          echo "La rama es: $GITHUB_REF_NAME"
          echo "El workflow es: $GITHUB_WORKFLOW"

      - name: "Generar archivo JSON"
        run: |
          echo '{' > resultado.json
          echo '  "Prueba de mensajes": {' >> resultado.json
          echo '    "mensaje": "Hola Grupo 5, bienvenidos"' >> resultado.json
          echo '  },' >> resultado.json
          echo '  "Variables creadas en el workflow": {' >> resultado.json
          echo '    "plataforma": "${{ env.plataforma }}",' >> resultado.json
          echo '    "region": "${{ env.region }}",' >> resultado.json
          echo '    "clase": "${{ env.clase }}"' >> resultado.json
          echo '  },' >> resultado.json
          echo '  "Variables del entorno de GitHub Actions": {' >> resultado.json
          echo '    "repositorio": "$GITHUB_REPOSITORY",' >> resultado.json
          echo '    "rama": "$GITHUB_REF_NAME",' >> resultado.json
          echo '    "workflow": "$GITHUB_WORKFLOW"' >> resultado.json
          echo '  },' >> resultado.json
          echo '  "Despedida": {' >> resultado.json
          echo '    "mensaje": "El workflow del Grupo 5 se ejecutó correctamente."' >> resultado.json
          echo '  }' >> resultado.json
          echo '}' >> resultado.json

      - name: "Mostrar archivo JSON"
        run: cat resultado.json

      - name: "Con Despedida"
        if: env.plataforma == 'reniec'
        run: |
         echo "Despedida: El workflow del Grupo 5 se ejecutó correctamente."
      
      - name: "Sin despedida"
        if: env.plataforma == 'aws'
        run: echo "Este mensaje NO se debe imprimir porque la condición es falsa."
