name: Grupo 5

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    env:
      plataforma: reniec
      region: piura
      clase: HDD
    
    runs-on: ubuntu-latest
    
    steps:
      - name: "Prueba de mensajes"
        run: echo "Hola Grupo 5, bienvenidos"

      - name: "Variables creadas en el workflow"
        run: |
          echo "La plataforma es: ${{ env.plataforma }}"
          echo "La región es: ${{ env.region }}"
          echo "La clase es: ${{ env.clase }}"

      - name: "Variables del entorno del Github Actions"
        run: |
          echo "El repositorio es: $GITHUB_REPOSITORY"
          echo "La rama es: $GITHUB_REF_NAME"
          echo "El workflow es: $GITHUB_WORKFLOW"
